services:
  database:
    container_name: "mariadb-dev"
    image: mariadb:12.3
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ${MYSQL_DB}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    command:
      - --character-set-server=utf8mb3
      - --collation-server=utf8mb3_general_ci